"""Определение исключений для модуля запросов."""


class ValidationError(Exception):
    """Исключение, возникающее при неудачной проверке."""
